services:
  # MongoDB for document storage
  mongodb:
    image: mongo:7.0
    container_name: video-intelligence-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: video-intelligence
    volumes:
      - mongodb_data:/data/db
    networks:
      - video-intelligence-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for caching and Celery broker
  redis:
    image: redis:7-alpine
    container_name: video-intelligence-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - video-intelligence-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ChromaDB for local vector database
  chromadb:
    image: chromadb/chroma:latest
    container_name: video-intelligence-chromadb
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - chromadb_data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
      - ANONYMIZED_TELEMETRY=FALSE
    networks:
      - video-intelligence-network
    # Disabled health check for now - ChromaDB API endpoints vary by version
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5

  # FastAPI application
  api:
    build:
      context: ./services/backend
      dockerfile: Dockerfile
    container_name: video-intelligence-api
    restart: unless-stopped
    ports:
      - "8003:8003"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/services/backend
      - PYTHONUNBUFFERED=1
      - MONGODB_URL=mongodb://mongodb:27017/video-intelligence
      - REDIS_URL=redis://redis:6379
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8000
    volumes:
      - ./services/backend:/services/backend
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
      chromadb:
        condition: service_started
    networks:
      - video-intelligence-network
    command: ["python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8003", "--reload"]

  # Celery worker
  worker:
    build:
      context: ./services/backend
      dockerfile: Dockerfile
    container_name: video-intelligence-worker
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PYTHONPATH=/services/backend
      - PYTHONUNBUFFERED=1
      - MONGODB_URL=mongodb://mongodb:27017/video-intelligence
      - REDIS_URL=redis://redis:6379
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8000
      - CELERY_WORKER_CONCURRENCY=4
      - CELERY_WORKER_MAX_MEMORY_PER_CHILD=2048000
    volumes:
      - ./services/backend:/services/backend
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
      chromadb:
        condition: service_started
    networks:
      - video-intelligence-network
    command: ["python", "-m", "celery", "-A", "celery_app", "worker", "--loglevel=info", "--concurrency=4", "--pool=threads"]

  # Optional: Flower for Celery monitoring
  flower:
    build:
      context: ./services/backend
      dockerfile: Dockerfile
    container_name: video-intelligence-flower
    restart: unless-stopped
    ports:
      - "5555:5555"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/services/backend
      - PYTHONUNBUFFERED=1
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
    networks:
      - video-intelligence-network
    command: ["python", "-m", "celery", "-A", "celery_app", "flower", "--port=5555"]

  # Test service for running tests with development databases
  test:
    build:
      context: .
      dockerfile: services/backend/Dockerfile
    container_name: video-intelligence-test
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      # Use development databases for testing
      MONGODB_URL: mongodb://mongodb:27017/video-intelligence-test
      REDIS_URL: redis://redis:6379/1  # Use different Redis DB
      
      # AWS credentials (will be mocked in tests)
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-test}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-test}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION:-us-east-1}
      S3_BUCKET: ${S3_BUCKET:-test-bucket}
      S3_OUTPUT_BUCKET: ${S3_OUTPUT_BUCKET:-test-output-bucket}
      
      # API keys (will be mocked in tests)
      OPENAI_API_KEY: ${OPENAI_API_KEY:-test}
      NVIDIA_API_KEY: ${NVIDIA_API_KEY:-test}
      
      # Other settings
      VECTOR_DB_TYPE: ${VECTOR_DB_TYPE:-milvus}
      ENVIRONMENT: test
      PYTHONPATH: /services/backend
      
    volumes:
      # Mount source code for live updates
      - ./services/backend:/services/backend
      # Mount test results
      - ./test-results:/test-results
    working_dir: /services/backend
    networks:
      - video-intelligence-network
    profiles:
      - test  # Only run when explicitly requested

networks:
  video-intelligence-network:
    driver: bridge

volumes:
  mongodb_data:
  chromadb_data: